/// <reference types="nativewind/types" />

/**
 * `expo/types` carries the `*.css` module declaration that the global
 * stylesheet's side-effect import in app/_layout.tsx needs.
 *
 * Expo normally supplies this through a generated `expo-env.d.ts`, but that
 * file is regenerated by the CLI and `expo prebuild --clean` deletes it — so
 * typecheck breaks on a fresh clone or straight after a prebuild. Referenced
 * here instead, from a file the repository owns.
 */
/// <reference types="expo/types" />
