-- The location's NAME, beside its address.
--
-- **No story defines this field.** `New Shoot.dc.html`'s second pass splits
-- «Локація» into «Назва» («Наприклад, Студія KULT»), «Адреса» («Вулиця,
-- будинок, місто») and «Деталі»; the owner asked for the column (2026-09-03).
-- `US-002` and `US-018` need amending.
--
-- It resolves a conflation rather than adding a concept. `location_address` has
-- carried both since the field's placeholder was «Назва або адреса» — the
-- location chips (`pastLocations`) put a venue name in it («Студія KULT») while
-- the shoot-detail screen offers to open the same value in Maps and to copy it
-- as an address. Those are two different values and one column.
--
-- `location_note` is untouched and is the third field, «Деталі». It already
-- meant "how to get in" (`US-018` AC-2) and the edit screen already collected
-- it as «Нотатки (як доїхати тощо)»; only its label moves.
alter table public.shoots
  add column location_name text;

-- No policy or grant change: `shoots_select_own` / `shoots_update_own` scope
-- every row to its creator, and this column inherits both.

-- ── On the link surface since 2026-09-03 ────────────────────────────────────
--
-- This column was deliberately kept OFF the anonymous payload when it was
-- added, on the stance `shoots.notes` set (20260830160000): no story says who
-- may see a venue's name, and omitting it is the reversible direction.
--
-- The owner asked for it the same day, after seeing the deployed link view show
-- an address with no venue above it. It is selected for **both** audiences now —
-- a venue's name is neither a note nor a contact, so `ADR-013`'s split does not
-- divide on it, and both audiences already receive `location_address` and
-- `location_note`. `US-026`'s "no notes field, not even an empty one" is
-- untouched.
--
-- **Still NOT in the ICS export** (`src/features/links/calendar.ts`), whose
-- `location` field carries the address alone. Nothing asked for it there and a
-- calendar entry wants something a map can resolve.
--
-- `crew_shoots()` (20260827100000) does not select it either — that function
-- feeds the creator's own «мої зйомки» list, which reads the column directly.
